version: "3.8"

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - database-data:/var/lib/mysql

  php-sandbox:
    image: php:7.4-apache
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always
    depends_on:
      - database

volumes:
  database-data: