version: "3.9"

services:
  database:
    image: mariadb
    env_file:
      - docker/env/project.env

  php-fpm:
    env_file:
      - docker/env/project.env
    build:
      context: docker/dockerfile/php-fpm
      args:
        USER_NAME: "Your Name"
        USER_EMAIL: "you@example.com"
    volumes:
      - ./application:/application
    working_dir: /application
    depends_on:
      - database

  webserver:
    image: nginx
    env_file:
      - docker/env/project.env
    volumes:
      - ./docker/templates:/etc/nginx/templates
      - ./application:/application
    working_dir: /application
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  node:
    image: node:12
    volumes:
      - ./application:/application
    working_dir: /application