version: "3.9"

services:
  database:
    image: postgres
    env_file:
      - docker/env/project.env
    ports:
      - "5432:5432"

  php-fpm:
    build: docker/dockerfile/php-fpm
    env_file:
      - docker/env/project.env
    volumes:
      - ./application:/application
    working_dir: /application
    depends_on:
      - database

  webserver:
    image: nginx
    env_file:
      - docker/env/project.env
    volumes:
      - ./docker/templates:/etc/nginx/templates
      - ./application:/application
    working_dir: /application
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  node:
    image: node:10
    volumes:
      - ./application:/application
    working_dir: /application
    depends_on:
      - webserver
    command: yarn encore dev --watch