version: "3.9"

services:
  mariadb:
    image: mariadb
    env_file:
      - docker/env/project.env
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  php-fpm:
    build: docker/dockerfile/php-fpm
    env_file:
      - docker/env/project.env
    volumes:
      - ./application:/application
    working_dir: /application
    depends_on:
      - mariadb

  webserver:
    image: nginx
    env_file:
      - docker/env/project.env
    volumes:
      - ./docker/templates:/etc/nginx/templates
      - ./application:/application
    working_dir: /application
    ports:
      - "80:80"
    depends_on:
      - php-fpm

volumes:
  mariadb-data: